### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by zeekoe** [emreyolcu/discrete-scroll#11]
This tool looks promising!
When running my self-compiled version I get a segmentation fault. When running from XCode, I get BAD_ACCESS most of the times. It seems that eventTap is 0x0. Any idea how?

**Comment by emreyolcu** [comment]
Could this be the same issue (permissions-related) as #9?

**Comment by zeekoe** [comment]
Yep, that's it! Thanks. Probably I needed to add the terminal, too. Got it working!
