### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by emretanriverdi** [emreyolcu/discrete-scroll#12]
Hi!

This is an amazing tool. I switched from Windows to MacOS Catalina and this scrolling behavior was really bugging me. I knew something was off, felt weird while scrolling and couldn't adapt it for 2 months.

Now I can safely use my MacBook which I really like using, so I wanted to show you my gratitude.

P.S.: We share the same names.:)

Thank you a lot,
Emre.

**Comment by emreyolcu** [comment]
I'm glad you find it useful!
