### ISSUE TITLE
Seems like it's not working on Catalina

### ISSUE THREAD

**Issue by dmitryrn** [emreyolcu/discrete-scroll#13]
MacOS version: 10.15.4 (19E287)
I launched it, but my mouse wheel scroll still work with acceleration

**Comment by pdemro** [comment]
10.15.5 (19F101) here, works as expected.  I needed to restart my browser

**Comment by emreyolcu** [comment]
@dmitryrn are you able to find the process in Activity Monitor by searching for "DiscreteScroll"? If so, could you check which version of the binary you downloaded? I believe v0.1.0 will not work on the newer versions of macOS.

**Comment by bb2020** [comment]
Another Catalina user here, works very well.

**Comment by dmitryrn** [comment]
Ok, I think I just forgot to reboot or something, cannot check again

**Comment by emreyolcu** [comment]
@dmitryrn should we close the issue? I cannot tell from your reply whether it is working or not.
