### ISSUE TITLE
crashes every time i try to launch it

### ISSUE THREAD

**Issue by iwa** [emreyolcu/discrete-scroll#14]
i had to make a fresh install of Catalina, and since, the program is no longer working :/
every time i launch the app, it's crashing (not showing up in the monitor + crash logs)

here's a gist with the crash logs (hope this can help)
https://gist.github.com/iwa/8aaee5e3eaabb94255fb74785138bf74

**Comment by iwa** [comment]
seems not to be working only on the 3 lines version of the program for some reasons

**Comment by emreyolcu** [comment]
Could you go to `System Preferences > Security & Privacy > Privacy > Accessibility` and make sure that `DiscreteScroll.app` appears on the list with a check next to it?

**Comment by iwa** [comment]
it still was checked, so i just tried to remove and add it again into the `Accessibility` panel, and it worked.. that's strange xD
anyways, thanks!
