### ISSUE TITLE
Working on macOS Catalina and Big Sur, thanks a million!

### ISSUE THREAD

**Issue by fpeterschmitt** [emreyolcu/discrete-scroll#15]
❤️

**Comment by DuckersMcQuack** [comment]
Nice! Thanks for confirming! and i love it as well! Bit too much with 3 lines, but helluva better than 3 pixels per tick with slow scrolling!

**Comment by runfaj** [comment]
This is working so much better (Big Sur 11.5.2)! I am finding it is scrolling about 8 lines per wheel tick in my code editor, but compared to before, it is SOOOOO much better.

**Comment by emreyolcu** [comment]
I'm glad it works for you all, but I'll try to close issues that report the tool as working to keep the issue list tidy.
