### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by cjh9** [emreyolcu/discrete-scroll#16]
How to build this project from command line? I'd rather not download and execute a binary :P should perhaps be added to the readme?

**Comment by emreyolcu** [comment]
I don't know how to build it from the command line, but you may instead import the project in Xcode and build it there.

**Comment by gramospear** [comment]
same concern here, DLed the binary though n works fine

**Comment by kambala-decapitator** [comment]
either install Xcode and use `xcodebuild` on the command line or try similar compile command to https://github.com/macegr/mtExtraButtons : `clang -framework ApplicationServices -o DiscreteScroll DiscreteScroll/main.m`

**Comment by ychin** [comment]
For those who are too lazy to read up on the exact command:

Build:
```
xcodebuild build -project DiscreteScroll.xcodeproj
```

Run:
```
open build/Release/DiscreteScroll.app
```

**Comment by jgspratt** [comment]
I was able to get the `xcodebuild build...` to work, however, running `open build/Release/DiscreteScroll.app` did nothing (nothing opened, saw no error messages).

I was able to get `clang -framework ApplicationServices -o DiscreteScroll DiscreteScroll/main.m` to build a binary and the binary did what I wanted (scroll 12 lines).

I am able to get it to stay open like this: `nohup ~/bin/DiscreteScrollBuild 2>&1 &`
