### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by Cyberbeni** [emreyolcu/discrete-scroll#17]
I'm pretty sure that the project just needs to be rebuilt with the latest Xcode to support ARM64 natively.

**Comment by Hatt3n** [comment]
It works on my M1 Mac Mini. Just download the project, import it to Xcode and build it. And yes, it will be native in this case.

**Comment by iwa** [comment]
Works perfectly fine if you manually re-build the project.

For the laziest here, I uploaded some native binaries in [my fork here](https://github.com/iwa/discrete-scroll-arm/releases/tag/v0.1.1u).
@Cyberbeni wanna try them out to tell me if they works fine for you?

**Comment by emreyolcu** [comment]
@iwa: Could you help me troubleshoot the following? I rebuilt the project, but I wanted to export the binary the proper way by choosing `Product > Archive` in Xcode and then choosing `Distribute App` followed by the `Copy App` option to place the binary in some folder. When I do this the supposed universal binary does not appear in the Activity Monitor after I try to run it. If I simply run the Debug build in Xcode it does run and function properly. Did you put the debug binaries or the distribution binaries in your fork? I would like to compile new ones and put them in this repository as well.

**Comment by emreyolcu** [comment]
I included universal binaries in [release v0.1.1u](https://github.com/emreyolcu/discrete-scroll/releases/tag/v0.1.1u).

**Comment by iwa** [comment]
@emreyolcu sry!!! I didn't see the mention notification and didn't check the issue till now 😭 
I had some troubles when testing the new version, I had to totally uninstall the old one and install the new universal, then restart, to make it work properly

anyways, it seems to bed fixed for you now, I'll be locking my fork and redirect the download link to yours now

**Comment by emreyolcu** [comment]
> @emreyolcu sry!!! I didn't see the mention notification and didn't check the issue till now 😭 I had some troubles when testing the new version, I had to totally uninstall the old one and install the new universal, then restart, to make it work properly
> 
> anyways, it seems to bed fixed for you now, I'll be locking my fork and redirect the download link to yours now

Thanks a lot for testing it!
