### ISSUE TITLE
Still working on Big Sur as of May 2021

### ISSUE THREAD

**Issue by gramospear** [emreyolcu/discrete-scroll#18]
Feel free to close this but actually the description or readme should atleast be updated to state that it still works as of late, with the age of the last commit I thought this might be out of commission.

Thankfully looking into the issues someone did say it was still working for them in 2019/2020

**Comment by emreyolcu** [comment]
That's a good idea, I will update it now. Also, I use this tool essentially everyday (not yet on Big Sur though), so if Apple changes/removes the API someday I will try to get it back working.
