### ISSUE TITLE
Add customisation point for number of lines scrolled

### ISSUE THREAD

**Issue by tpgillam** [emreyolcu/discrete-scroll#19]
Firstly, thank you for this amazingly useful utility!

I find myself wanting to customise the number of lines that are scrolled at once (3 being a little too small for most applications for me). I see it's currently #defined at the top of the file; maybe it could be (optionally) read from the command line? [Or even a configuration file, but that might be overkill]

**Comment by emreyolcu** [comment]
I like keeping it minimal and completely out of sight, but here is a configurable menu bar version by @gavinlynch: https://github.com/gavinlynch/scroll-sanity

**Comment by tpgillam** [comment]
Fair enough; thanks for the recommendation!
