### ISSUE TITLE
Requesting more scrolling options.

### ISSUE THREAD

**Issue by DuckersMcQuack** [emreyolcu/discrete-scroll#21]
Not an issue per say, but may i request 3 releases for this tool? One for 1 line, one for 2 lines and one for 3 lines per scrolling tick so we can choose at what speed we want as default :)

**Comment by emreyolcu** [comment]
This is already part of the last release, see the additional binaries at https://github.com/emreyolcu/discrete-scroll/releases/tag/v0.1.1.
