### ISSUE TITLE
Any chance this could get signed?

### ISSUE THREAD

**Issue by alaricljs** [emreyolcu/discrete-scroll#23]
Any possibility of getting a version of this binary signed so that I can bypass "can't be opened because Apple cannot check it for malicious software"?  My support guy is looking into whether not being able to bypass this is part of any of the security products we run, but I can't just 'Open Anyway'.

I'm on MacOS 11.5.2

Thanks!

**Comment by kambala-decapitator** [comment]
right-clicking the binary should allow opening it. Or just build it from the source.

**Comment by emreyolcu** [comment]
I will probably not get it signed since that appears to require me to enroll in the paid Apple Developer Program.
