### ISSUE TITLE
Can't run binary on Big Sur—I get a "The application 'DiscreteScroll.app' can't be opened: 11" message

### ISSUE THREAD

**Issue by eriegz** [emreyolcu/discrete-scroll#25]
Steps to reproduce:

- Navigate to [discrete-scroll GitHub repo](https://github.com/emreyolcu/discrete-scroll)
- Download the [binary](https://github.com/emreyolcu/discrete-scroll/releases/download/v0.1.1/DiscreteScroll.zip)
- Unzip the file
- Drag "DiscreteScroll.app" to the /Applications folder
- Double-click / <kbd>Cmd</kbd> + <kbd>O</kbd> the app
- Get a "This app was downloaded from the internet... etc." pop-up, click "OK"

Expected outcome:

- App runs

Actual outcome:

- I get a "The application 'DiscreteScroll.app' can't be opened: 11" dialog window
<img src="https://user-images.githubusercontent.com/10801672/144330836-54489566-f4c0-4028-acf5-78b8999c9d5a.png" width=400/>

**Note:** I did get a slightly different pop-up window the very first time I tried running the binary. It contained a button taking me to my System Preferences, but there was no "Allow" or "Run anyway" section under the "Privacy > General" tab where I expected it to be, so I just closed Sys Prefs and tried again. But now I can't seem to get that window anymore.

Also, the app does not appear in my Activity Monitor list.

**Comment by emreyolcu** [comment]
Are you using a laptop with the M1 CPU? That is my only guess for the cause of this problem. If you have Xcode, could you try recompiling the binary? Otherwise, could you try running the [binaries](https://github.com/iwa/discrete-scroll-arm/releases/tag/v0.1.1u) from @iwa's fork?

**Comment by eriegz** [comment]
> Are you using a laptop with the M1 CPU?

Nope, Intel.
<img src="https://user-images.githubusercontent.com/10801672/144467829-a7381a3a-5548-4f1a-bcd2-8556226b43b3.png" width="700">

> If you have Xcode, could you try recompiling the binary?

I don't have Xcode, so I tried the other binaries you linked, and here's the result:

- Unzip, drag to /Applications, etc.
- <kbd>Cmd</kbd> + <kbd>O</kbd>, I get this message:
<img src="https://user-images.githubusercontent.com/10801672/144473949-60a03df5-f303-40ff-aa82-27e20184cfc5.png" width="400" />
- So then I click "OK" and manually go to System Preferences > Security & Privacy, and now I see the usual message that I'm expecting:
<img src="https://user-images.githubusercontent.com/10801672/144474167-6107453f-769f-416d-bb65-84881ed7c036.png" width="700" />
- So I click "Open Anyway", but then I get this dialog:
<img src="https://user-images.githubusercontent.com/10801672/144474245-ce10c2d8-0043-41db-8db7-d860aad0a5e6.png" width="400">
- So I click "Open" and nothing happens, so I check Activity Monitor, and still no "DiscreteScroll" in the list

**Comment by emreyolcu** [comment]
Thanks for the detailed description. It seems that macOS is getting more and more annoying about the distribution of unsigned binaries. Could you try running the binary by Control-clicking and choosing Open from the menu instead of Command + O? Apple's own guide suggests doing that. See https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/11.0/mac/11.0.

**Comment by eriegz** [comment]
@emreyolcu Just tried, but same behaviour.

Also, I don't think there's anything special about Ctrl + Click > "Open", necessarily. I think Apple just specifies that in that document to ensure users are looking in the right place (Ctrl + Click is the "standard" way to open up the context menu in macOS).

**Comment by emreyolcu** [comment]
Then installing Xcode and compiling from the source is the only solution I can offer. It is curious that nobody else reported this problem—Big Sur has been out for a year now. (I am on 10.15.7.) The message says that "Apple cannot check it for malicious software". I remember reading that, at least as of Big Sur, macOS silently phones home for every program you run. Maybe it is a temporary problem or a specific issue with your network. Are you able to run other fresh (to your OS) unsigned binaries?

**Comment by ShengChangYang** [comment]
I think the issue caused by Gatekeeper.
I am using Big Sur that run on M1 MacBook Air but I disabled the Gatekeeper.
So, I didn't encounter this issue with [GitHub released binary](https://github.com/emreyolcu/discrete-scroll/releases/).
Maybe @eriegz can refer to [this article](https://www.cnet.com/tech/computing/how-to-manage-os-x-gatekeeper-from-the-command-line/) to allow specific app.

**Comment by eriegz** [comment]
Alright so I tried building from source and running it that way, but unfortunately I get the exact same outcome:

**Steps to reproduce:**
 
- Installed Xcode
- [Pointed xcode-select to the Xcode app Developer directory](https://stackoverflow.com/questions/17980759/xcode-select-active-developer-directory-error/17980786#17980786):
  - `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`
- Followed [the only documentation I could find](https://github.com/emreyolcu/discrete-scroll/issues/16) on how to build from source:
  - `xcodebuild build -project DiscreteScroll.xcodeproj`
    - I get a "** BUILD SUCCEEDED **" message
  - `open build/Release/DiscreteScroll.app`
 
**Expected outcome:**
 
- Application should run
- Application should be listed in "Activity Monitor" under "DiscreteScroll"
 
**Actual outcome:**

- Nothing at all happens (same as when I simply tried running the downloaded binary)

Are there any logs I can access to see what's going on?

**Comment by eriegz** [comment]
***Phew!*** So I finally got it to work, but I'm not sure what exactly fixed the problem:

1. [disabling GateKeeper just for DiscreteScroll.app via terminal](https://disable-gatekeeper.github.io/), and restarting my computer, or
2. Clearing out the "*System software from developer "Box, Inc." has been updated.*" item from my System Preferences > Security & Privacy > General blocked items (see above screenshots), and restarting

In any case, putting my steps below to hopefully help anybody else:

- Restarted computer
- Double-clicked "DiscreteScroll.app" in /Applications folder once more
<img src="https://user-images.githubusercontent.com/10801672/145117731-a7944c2d-fb88-43e8-b070-fd87c89415e9.png" width="500" />

- Clicked "Open System Preferences"
- System Preferences opened up with the "Privacy" tab selected (***note:** Previous steps would only ever take me to the "General" tab when clicking the security pop-ups*)

<img src="https://user-images.githubusercontent.com/10801672/145117765-9712e6f3-63ab-46d3-a61a-cfb6e1fa6466.png" width="700" />

- Clicked lock icon to make changes, entered password, etc.
- Then as you can see there were duplicate entries in list because I was trying to run it both from binary and from built source, so I just deleted both and re-launched the app from /Applications (because otherwise no way to tell which is which)
- After launching app again, clicked "Open System Preferences" and navigated to "Privacy" tab once more
- Enabled "DiscreteScroll.app":

<img src="https://user-images.githubusercontent.com/10801672/145117944-b6805a37-cc91-499a-9e06-d2d6847ca622.png" width="700" />

- Went back to Applications folder and double-clicked "DiscreteScroll.app"
- Opened Activity Monitor, and finally DiscreteScroll.app is in the list!
- Tested out scrolling in Chrome; everything works! 🥳🎉

**Comment by emreyolcu** [comment]
Glad it works, and thanks once again for your detailed comments. Hopefully this procedure won't get more problematic with future releases. I ran this for the first time on 10.9.5 and even the Accessibility permissions were not required then.
