### ISSUE TITLE
1 line and 2 lines versions don't work

### ISSUE THREAD

**Issue by luca-iliev** [emreyolcu/discrete-scroll#26]
I don't know why but the one line and the two line versions don't work, they don't even show in the activity monitor. No problems for the three lines version, but i'd like to try the other ones, three lines are too many for my mouse

**Comment by emreyolcu** [comment]
Perhaps this is related to #25. Could you try following the steps that @eriegz outlined in that issue?

**Comment by luca-iliev** [comment]
I solved using these versions https://github.com/iwa/discrete-scroll-arm/releases/tag/v0.1.1u
