### ISSUE TITLE
Is it possible to change the amount of lines it scrolls at once?

### ISSUE THREAD

**Issue by PixelByteDrive** [emreyolcu/discrete-scroll#28]
I've been trying to modify the program to change the amount of lines it scrolls, since 3 is too fast for modern usage.
Is there a native way to do it or do I have to modify the entire program?

**Comment by emreyolcu** [comment]
There are two more binaries [here](https://github.com/emreyolcu/discrete-scroll/releases/tag/v0.1.1) that scroll 1 or 2 lines.

**Comment by PixelByteDrive** [comment]
Those binaries are non-functional when I run them.

**Comment by emreyolcu** [comment]
I would recommend checking out the previously closed issues for solutions, in particular #26 and #25 depending on your exact configuration.

**Comment by TheKodeToad** [comment]
Is there a way to increase the scroll speed? 3 lines feels very slow compared to using the same mouse on both Linux and Windows.

**Comment by bandtank** [comment]
@TheKodeToad It is listed in the README. You can change the number of lines per scroll to be whatever you want.

**Comment by robbporto** [comment]
> It is listed in the README

Where? I can't see any mentions of this in the README.

**Comment by emreyolcu** [comment]
> > It is listed in the README
> 
> Where? I can't see any mentions of this in the README.

It is not mentioned there. To increase the number of lines scrolled per tick, you can change the value [here](https://github.com/emreyolcu/discrete-scroll/blob/a4c1d5e8ae99611de5f9edff25aaa2d09d250a27/DiscreteScroll/main.m#L4) and recompile. If you do not want to install Xcode, then I suggest using @gavinlynch's [implementation](https://github.com/gavinlynch/scroll-sanity), which has an interface for customization.
