### ISSUE TITLE
This is a tiny but great app

### ISSUE THREAD

**Issue by aphasia0** [emreyolcu/discrete-scroll#30]
First thanks for this, I love this application. Scrolling experience with my mouse was so bad before using this app.

I was wondering how much effort it is to add a simple bar icon on top with the option to keep the application running always. I'm a programmer but I'm not familiar with Objective-C.

**Comment by emreyolcu** [comment]
If by "running always" you mean "start at login," then you may go to System Preferences > Users & Groups > Login Items and add the executable to the list. As for the menu bar icon, I prefer to keep the application completely out of sight. In my comment [here](https://github.com/emreyolcu/discrete-scroll/issues/29#issuecomment-1136256115), I pointed to alternatives for those interested in full-fledged applications that fix this issue (and more). I have not tried any of them, but [LinearMouse](https://github.com/linearmouse/linearmouse) seems pretty nice and minimal.
