### ISSUE TITLE
Application is not working after update

### ISSUE THREAD

**Issue by ghost** [emreyolcu/discrete-scroll#31]
I have used v0.1.1 almost year on macbook air 2020 m1 and it have works fine all this time.

I have update application via brew and now it's not working. I have delete/install it several times, but without result.

Also i try to install previous version via
`brew install discretescroll@0.1.1` - but it is only one version there.

I have try:
- install application via brew and run - it's not starting;
- install application v0.1.1u manually from github and run - it's not starting;
- install application v0.1.1 manually from github and run - it's working!;

So please:
- fix the application release;
- add version support to brew;

Macos Ventura 13.0.1

**Comment by veloek** [comment]
@fatescreen Same here. Was excited to see an arm64 build, but it didn't work for me either.

Tried to run the binary inside `Contents/MacOS/` in a terminal, but to no avail:
```
$ ./DiscreteScroll
zsh: segmentation fault  ./DiscreteScroll
```

Running the program with lldb revealed an `EXC_BAD_ACCESS` error:
```
$ lldb --file ./DiscreteScroll
(lldb) target create "./DiscreteScroll"
Current executable set to '/Applications/DiscreteScroll.app/Contents/MacOS/DiscreteScroll' (arm64).
(lldb) r
Process 75114 launched: '/Applications/DiscreteScroll.app/Contents/MacOS/DiscreteScroll' (arm64)
Process 75114 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x8)
    frame #0: 0x0000000188e16224 CoreFoundation`_CFGetNonObjCTypeID + 92
CoreFoundation`:
->  0x188e16224 <+92>:  ldar   x8, [x8]
    0x188e16228 <+96>:  ubfx   x8, x8, #8, #10
    0x188e1622c <+100>: b      0x188e162c4               ; <+252>
    0x188e16230 <+104>: cmp    x9, #0x7
Target 0: (DiscreteScroll) stopped.
```

@emreyolcu Any clue as to what's going on here?

**Comment by emreyolcu** [comment]
That's weird. When I run the application bundle (not the binary—I think that segfault is expected) on my Intel-based system it works without any issues. Also, another user (see https://github.com/emreyolcu/discrete-scroll/issues/17#issuecomment-1337785817) tested the new version and reported that, after they removed the previous version and restarted, it was running properly.

To rule out issues with permissions, could you try the following?

- Run Activity Monitor, search for "DiscreteScroll", and kill the process.
- Remove the old version (in case it is set to launch automatically on login).
- Go to Security & Privacy > Privacy > Accessibility and remove "DiscreteScroll.app" from the list. Then add the newly downloaded version to the list.
- Restart.

**Comment by veloek** [comment]
@emreyolcu  Seems to be working after a uninstall -> reboot -> install 👍
