### ISSUE TITLE
Could you make the executable compatible with ARM64 (M1 / M2 ++ processors) ?

### ISSUE THREAD

**Issue by 0xInuarashi** [emreyolcu/discrete-scroll#32]
Would be highly appreciated. Thanks! :)

**Comment by emreyolcu** [comment]
[Release v0.1.1u](https://github.com/emreyolcu/discrete-scroll/releases/tag/v0.1.1u) should be compatible with ARM64.

**Comment by 0xInuarashi** [comment]
Ops, I saw that the actual release v0.1.1u already does this. However, the description was linked to v0.1.1 that does not support the Apple Silicon. Thank you!

**Comment by emreyolcu** [comment]
> Ops, I saw that the actual release v0.1.1u already does this. However, the description was linked to v0.1.1 that does not support the Apple Silicon. Thank you!

I fixed that, thanks for noticing.
