### ISSUE TITLE
[Feature] Fix macOS's unnecessary mouse acceleration 

### ISSUE THREAD

**Issue by ChristopherHaws** [emreyolcu/discrete-scroll#33]
Any chance we can get a second app that is as simple as this one that fixes mac's crazy mouse acceleration curve? The combo of these two things would fix mouse support in macOS. Coming from Windows and Linux, it feels like the mac dev team created the best trackpad by not spending any time on making modern mice work with their OS.

Thanks for this simple fix!

**Comment by Zekfad** [comment]
You can use `SteelSeries ExactMouse Tool` for that. Although it's outdated (made back in 2010), it's still working fine.

**Comment by ivan** [comment]
I've used https://plentycom.jp/en/cursorsense/

**Comment by ChristopherHaws** [comment]
Currently I am using [Smooze Pro](https://smooze.co/) which works well, but was hoping for a free and open source solution that is actively maintained.

**Comment by 0xInuarashi** [comment]
This one is quite small, open source, and nice https://github.com/apsun/NoMouseAccel

**Comment by emreyolcu** [comment]
This was fixed by Apple in macOS 14. They added an option to disable mouse acceleration.
