### ISSUE TITLE
[FR] Can we make the number of lines configurable?

### ISSUE THREAD

**Issue by lmai5** [emreyolcu/discrete-scroll#37]
As the title states, can we allow the number of lines configurable? 3 lines at a time is a bit slow to me.

**Comment by sula7** [comment]
Seems like it's possible to do it yourself by changing this [line](https://github.com/emreyolcu/discrete-scroll/blob/master/DiscreteScroll/main.c#L4) of code and rebuilding the app

**Comment by lmai5** [comment]
I've tried to build the app using Product > Archived app and got the built file now but it seems not running when I open it (not see it in Activity Monitor). I'm not sure if I missed something as I'm not really familiar with MacOS app.

**Comment by lmai5** [comment]
@emreyolcu @core-code

**Comment by lmai5** [comment]
I think I'm facing the same issue with #40

**Comment by emreyolcu** [comment]
Please see the instructions I have recently added to the README. If you would like to change (without recompiling) the number of lines scrolled, I listed some newer, feature-filled alternatives [here](https://github.com/emreyolcu/discrete-scroll/issues/29#issuecomment-1136256115). I have not used any of those, but you might prefer them.
