### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by sula7** [emreyolcu/discrete-scroll#42]
Hi,
I use discrete-scroll since [v0.1.1u](https://github.com/emreyolcu/discrete-scroll/releases/tag/v0.1.1u) and it's awesome utility that helps me to work with comfort on my MBP using regular mouse.

As I'm not C software engineer (but the Go/Golang), I'd like to contribute to this project financially.
Hope I'm not the only one who thinks the same.

**Comment by emreyolcu** [comment]
That's very thoughtful of you, thanks! Feel free to contribute via [PayPal](https://paypal.me/YolcuEmre).
