### ISSUE TITLE
add support for macos sequoia

### ISSUE THREAD

**Issue by kitiki1222** [emreyolcu/discrete-scroll#43]

**Comment by chefnaphtha** [comment]
it works on sequoia

**Comment by emreyolcu** [comment]
Thanks for confirming @chefnaphtha; I'll close the issue and update the README. I'm still on an older version of macOS and couldn't check it myself.

**Comment by kitiki1222** [comment]
> it works on sequoia

well for me it doesn’t work it says this 
![Image 11-11-24 at 10 36 PM](https://github.com/user-attachments/assets/affd88f2-b8a5-4ade-b8bf-47dc978bbe14)

**Comment by kitiki1222** [comment]
> > it works on sequoia
> 
> well for me it doesn’t work it says this ![Image 11-11-24 at 10 36 PM](https://private-user-images.githubusercontent.com/113810633/385130818-affd88f2-b8a5-4ade-b8bf-47dc978bbe14.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzODM0MTgsIm5iZiI6MTczMTM4MzExOCwicGF0aCI6Ii8xMTM4MTA2MzMvMzg1MTMwODE4LWFmZmQ4OGYyLWI4YTUtNGFkZS1iOGJmLTQ3ZGM5NzhiYmUxNC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTJUMDM0NTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWZmZDYwODNjMzQ5OGU4OGY4MjBhMGViYTI2YWNjMzE1NWE0YTkzNjgyYmQwNDk2MTQ1N2Q2ZTU0OGZkYmJkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.VPZ7ebTQA4mWYCcEjrGmN7gc9Bpw4U3Trx_nJhrhueo)

nevermind i fixed it
