### ISSUE TITLE
Scroll speed

### ISSUE THREAD

**Issue by chimit** [emreyolcu/discrete-scroll#5]
Please, could you add an option to set a scroll speed (number or rows to scroll per one wheel "movement")?

**Comment by olescheller** [comment]
@emreyolcu Any plans to build a small UI for this awesome little app?

**Comment by gavinlynch** [comment]
@oscheller1 @emreyolcu I've updated this for Swift 4 and added a menu bar based UI

https://github.com/gavinlynch/scroll-sanity

![screen shot 2018-04-23 at 10 45 08 am](https://user-images.githubusercontent.com/1050710/39137701-e29c87d0-46e3-11e8-8ab1-b2e529254da8.png)
![screen shot 2018-04-23 at 10 45 26 am](https://user-images.githubusercontent.com/1050710/39137702-e2b15e80-46e3-11e8-9519-07cd5318acb7.png)

**Comment by emreyolcu** [comment]
This is great, thanks a lot!
