### ISSUE TITLE
Changing scroll direction skips the first scroll wheel movement

### ISSUE THREAD

**Issue by olescheller** [emreyolcu/discrete-scroll#6]
When scrolling up and down using the scroll wheel, the first movement of the scroll wheel into the opposite direction is ignored and no scroll into that direction is executed.

**Comment by olescheller** [comment]
This seems to be a problem only in macOS Sierra. It does not occur on macOS El Capitan.

**Comment by emreyolcu** [comment]
I cannot reproduce it on OS X 10.9.5 either. Have you had a chance to try it on High Sierra?

**Comment by olescheller** [comment]
Yes, got the 2017 MacbookPro running High Sierra. Installing xcode right now and will report back when finished.

Just came across realizing that this problem does not occuring on my old MacPro 2009, which can not install Sierra. Back when I reported this issue I was (and still am) running this app on my work MacbookPro which is running the old Sierra (and still faces the reported issue).

EDIT: I just realize, I'm not able to connect my USB mouse to the new Macbook... Won't be able to test this for another few days unfortunately.

**Comment by olescheller** [comment]
I just got my USB adapter. The problem does not occur on this MacBook with High Sierra. This leads me to believe that the problem might have another origin. I'll test this on Sierra with another mouse later this week. I expect it to be a hardware issue for now.

**Comment by olescheller** [comment]
This is not caused by faulty hardware. Looks like it's simply misbehaving on Sierra.

`cgEventCallback` does not fire for the first mouse wheel movement in the opposite direction.

**Comment by olescheller** [comment]
Once again I need to correct myself. It was a hardware issue with certain Logitech mice (M-U0007). So it's neither macOS Sierra's, nor DiscreteScrolls fault ;-)
